### ISSUE TITLE
Improved courses REST API endpoint

### ISSUE THREAD

**Issue by cyrildewit** [cyrildewit/dnh-leer-platform#13]
## Todo

* [x] Use Spatie's QueryBuilder for `@index`
    * [x] Exact filters: id, slug
    * [x] Normal: title, headline, description, description_excerpt
   * [x] Allowed includes: topic, chapters, authors
* [x] Refactor the `getBySlug` method, so we can achieve it via a more generic way
* [x]  Use Spatie's QueryBuilder for `@show`
* [x] Rename `enrollCourse` action to `enroll`
